version: '3.8'

services: 
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    env_file: ./api-gateway/.env
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

auth-service:
  build: ./auth-service
  env_file: ./auth-service/.env
  depends_on:
    - redis
  environment:
    - REDIS_URL=redis://redis:6379